language: java

jdk:
  - openjdk11

cache:
  directories:
    - .autoconf
    - $TRAVIS_HOME/.m2

install: true

addons:
  sonarcloud:
    organization: "openwms-github"

script:
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) ]]; then mvn clean package sonar:sonar -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -Psonar -U; fi
  - mvn package -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -U
  - if [[ ( "$TRAVIS_BRANCH" == "master" ) ]]; then mvn clean package -Denforcer.skip=true -DskipTests=true -Dci.buildNumber=$TRAVIS_BUILD_NUMBER -Prelease,gpg; fi
